export const ContactStates = {
    CONTACTED: 'CONTACTED',
    NOT_CONTACTED: 'NOT CONTACTED',
    NOT_INTERESTED: 'NOT INTERESTED',
    INTERESTED: 'INTERESTED',
    WAITING_FOR_CALLBACK: 'WAITING FOR CALLBACK',
}

